# app/config/config.yml
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: no-reply@example.com
    sender_name: no-reply@example.com